### ISSUE TITLE
👷 Add travis integration and auto publishing

### ISSUE THREAD

**Issue by xaviervia** [batata-frita/lada#5]

**Comment by deepsweet** [comment]
Auto publishing is a tricky one because Travis can't publish packages from monorepo. I already have some workaround but haven't tested it yet (need it for @hocs as well).

**Comment by deepsweet** [comment]
My idea is based on a [custom deployment script](https://docs.travis-ci.com/user/deployment/script/) which will parse a git tag (with monorepo tags should follow `my-package@0.1.0` format) and then do a `npm publish packages/my-package`.

Also because it's a custom script we need to `npm login` with Travis first. There is a way do to this with something like `echo $MY_TRAVIS_AUTH_TOKEN .npmrc` but I haven't tried it yet. Works just like "cookie inject" from another already logged-in session.

**Comment by deepsweet** [comment]
It's too early for Travis, I need to create our Start preset first.

**Comment by deepsweet** [comment]
I just disabled for a while :) Maybe tomorrow.
